apiVersion: apps/v1
kind: Deployment
metadata:
  name: def-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: def-redis
  template:
    metadata:
      labels:
        app: def-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: def-redis
spec:
  selector:
    app: def-redis
  ports:
    - port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: def-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: def-kafka
  template:
    metadata:
      labels:
        app: def-kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.6
          env:
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: def-zookeeper:2181
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://def-kafka:9092
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
          ports:
            - containerPort: 9092
          volumeMounts:
            - mountPath: /bitnami/kafka
              name: kafka-data
      volumes:
        - name: kafka-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: def-kafka
spec:
  selector:
    app: def-kafka
  ports:
    - port: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: def-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: def-zookeeper
  template:
    metadata:
      labels:
        app: def-zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:3.9
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          ports:
            - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: def-zookeeper
spec:
  selector:
    app: def-zookeeper
  ports:
    - port: 2181
